### ISSUE TITLE
Comments Return JSON

### ISSUE THREAD

**Issue by delgado1567** [moore3071/moore3071.github.io#5]
Malide, Commenting on your site currently results in a JSON response from staticman.net to your user's web browser. You probably want the site to reload the page commented on instead as a temporary fix until you can get your front end code set up to properly handle the JSON. Hit this issue in version 55.0.3 with Ublock Origin enabled but even after disabling UBlock it was still returning only a JSON response.
![commentresponse](https://user-images.githubusercontent.com/14061393/30005265-a0106a96-90ac-11e7-9644-f004b75a21ab.JPG)
![commentresponse2](https://user-images.githubusercontent.com/14061393/30005266-a010e796-90ac-11e7-888c-51e9f6f66920.JPG)
![commentresponse3](https://user-images.githubusercontent.com/14061393/30005264-a00eb4e4-90ac-11e7-98a6-3f55c9174d48.JPG)

**Comment by delgado1567** [comment]
Also, apologies for the double comment on your password article. It did not seem to post the first time I submitted it so I posted it again.

**Comment by moore3071** [comment]
No worries on the double post. Thanks for bringing this issue up; I ran into it earlier and completely forgot to come back and fix it. I've pushed a fix that should work for now in 35f3cd5. I've also made a new issue for further enhancements as #6
